apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  replicas: 1
  template:
    metadata:
      name: node-exporter
      labels:
        app: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9100
      restartPolicy: Always
  selector:
    matchLabels:
      app: node-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  selector:
    app: node-exporter
  ports:
    - port: 9100
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:
    team: course
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
    - targetPort: 9100
      interval: 12s
      scrapeTimeout: 12s